server:
  port: 9999

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    data-username: root
    data-password: 535586

mybatis:
  config-location: classpath:mybatis-config.xml